scheduler_interval_minutes: 10
alert_threshold_percents: [5, 10, 20]

email:
  is_feature_enabled: True
  sender: "your_email_here@gmail.com"
  password: "your_app_password_here"
  smtp_server: "smtp.example.com"
  smtp_port: 587
  recipient_emails:
    - "recipient1@example.com"
    - "recipient2@example.com"
